version: '3.8'

services:
  server:
    image: python:3.10
    container_name: python_server
    command: >
      sh -c "pip install flask &&
             python -m flask run --host=0.0.0.0 --port=5000"
    environment:
      FLASK_APP: hello.py
    volumes:
      - ./app:/app
    working_dir: /app

  client:
    image: curlimages/curl
    container_name: curl_client
    command: ["sh", "-c", "sleep 5 && curl http://server:5000"]
    depends_on:
      - server


